# Generated by Django 3.1.3 on 2020-11-17 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(max_length=40)),
                ('post_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 17, 16, 29, 31, 338569))),
                ('post_image', models.ImageField(upload_to='blog_post_images/')),
                ('post_text', models.TextField(max_length=300)),
            ],
        ),
    ]
